name: release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:

  build:
    env:
      apt-dependencies: |
        autoconf automake docbook-xml docbook-xsl ebtables intltool ipset \
        iptables libdbus-1-dev libgirepository1.0-dev libglib2.0-dev \
        libxml2-utils nftables pkg-config python3-nftables xsltproc

    runs-on: ubuntu-20.04
    permissions:
      contents: write

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: apt update
        run: sudo apt update

      - name: apt install dependencies
        run: sudo apt install -y ${{ env.apt-dependencies }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: dist firewalld
        run: |
          ./autogen.sh
          ./configure
          make dist

      - uses: actions/upload-artifact@v4
        with:
        name: firewalld
        path: ["firewalld-*.tar.bz2"]
